config:
  dl4miceverywhere:
    notebook_url: https://raw.githubusercontent.com/tituslabumn/FiloVision_copy/refs/heads/main/250505_filoTips.ipynb
    requirements_url: https://raw.githubusercontent.com/tituslabumn/FiloVision_copy/refs/heads/main/20250430_filoTips_Requirements.txt
    cuda_version: 11.8.0
    cuda_version:  8.6.0.163
    ubuntu_version: '22.04'
    python_version: '3.10'
    sections_to_remove: 
    description: filoVision notebook. 
    notebook_version: 0.0.1